/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param activationCode 
 * @param email 
 * @param mobile 
 * @param password 
 * @param registrationType 
 * @param tag 
 * @param username 
 */
data class ActivationDto (

    val activationCode: kotlin.String? = null,
    val email: kotlin.String? = null,
    val mobile: kotlin.String? = null,
    val password: kotlin.String? = null,
    val registrationType: ActivationDto.RegistrationType? = null,
    val tag: kotlin.String? = null,
    val username: kotlin.String? = null
) {
    /**
    * 
    * Values: APPLEONESTEP,APPLETWOSTEP,EMAILCODE,EMAILLINK,EMAILOTP,FACEBOOKONESTEP,GOOGLEONESTEP,GOOGLETWOSTEP,LINKEDINONESTEP,LINKEDINTWOSTEP,SMSCODE,SMSLINK,SMSOTP
    */
    enum class RegistrationType(val value: kotlin.String){
        APPLEONESTEP("APPLE_ONE_STEP"),
        APPLETWOSTEP("APPLE_TWO_STEP"),
        EMAILCODE("EMAIL_CODE"),
        EMAILLINK("EMAIL_LINK"),
        EMAILOTP("EMAIL_OTP"),
        FACEBOOKONESTEP("FACEBOOK_ONE_STEP"),
        GOOGLEONESTEP("GOOGLE_ONE_STEP"),
        GOOGLETWOSTEP("GOOGLE_TWO_STEP"),
        LINKEDINONESTEP("LINKED_IN_ONE_STEP"),
        LINKEDINTWOSTEP("LINKED_IN_TWO_STEP"),
        SMSCODE("SMS_CODE"),
        SMSLINK("SMS_LINK"),
        SMSOTP("SMS_OTP");
    }
}