/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.BankCardExtraInfoDto

/**
 * 
 * @param cvv2 
 * @param expirationMonth 
 * @param expirationYear 
 * @param extraInfo 
 * @param id 
 * @param number 
 * @param selected 
 * @param sheba 
 */
data class BankCardDto (

    val cvv2: kotlin.String? = null,
    val expirationMonth: kotlin.Int? = null,
    val expirationYear: kotlin.Int? = null,
    val extraInfo: BankCardExtraInfoDto? = null,
    val id: kotlin.String? = null,
    val number: kotlin.String? = null,
    val selected: kotlin.Boolean? = null,
    val sheba: kotlin.String? = null
) {
}