/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param active 
 * @param id 
 * @param merchantId 
 * @param name 
 * @param type 
 */
data class BankGatewayDto (

    val active: kotlin.Boolean? = null,
    val id: kotlin.String? = null,
    val merchantId: kotlin.String? = null,
    val name: kotlin.String? = null,
    val type: BankGatewayDto.Type? = null
) {
    /**
    * 
    * Values: PAYMONGO,SEP,STRIPE,TEJARAT,TEST,ZARRINPAL
    */
    enum class Type(val value: kotlin.String){
        PAYMONGO("PAYMONGO"),
        SEP("SEP"),
        STRIPE("STRIPE"),
        TEJARAT("TEJARAT"),
        TEST("TEST"),
        ZARRINPAL("ZARRIN_PAL");
    }
}