/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param city 
 * @param country 
 * @param fullName 
 * @param state 
 * @param zipCode 
 */
data class BankCardAddressDto (

    val address: kotlin.String? = null,
    val city: kotlin.String? = null,
    val country: kotlin.String? = null,
    val fullName: kotlin.String? = null,
    val state: kotlin.String? = null,
    val zipCode: kotlin.String? = null
) {
}