/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param name 
 * @param ownerCampaignType 
 * @param ownerChargeType 
 * @param ownerChargeValue 
 * @param targetCampaignType 
 * @param targetChargeType 
 * @param targetChargeValue 
 */
data class CampaignInDto (

    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val ownerCampaignType: CampaignInDto.OwnerCampaignType? = null,
    val ownerChargeType: CampaignInDto.OwnerChargeType? = null,
    val ownerChargeValue: kotlin.Long? = null,
    val targetCampaignType: CampaignInDto.TargetCampaignType? = null,
    val targetChargeType: CampaignInDto.TargetChargeType? = null,
    val targetChargeValue: kotlin.Long? = null
) {
    /**
    * 
    * Values: DISCOUNT,WALLET
    */
    enum class OwnerCampaignType(val value: kotlin.String){
        DISCOUNT("DISCOUNT"),
        WALLET("WALLET");
    }
    /**
    * 
    * Values: CREDIT,PERCENT,VALUE
    */
    enum class OwnerChargeType(val value: kotlin.String){
        CREDIT("CREDIT"),
        PERCENT("PERCENT"),
        VALUE("VALUE");
    }
    /**
    * 
    * Values: DISCOUNT,WALLET
    */
    enum class TargetCampaignType(val value: kotlin.String){
        DISCOUNT("DISCOUNT"),
        WALLET("WALLET");
    }
    /**
    * 
    * Values: CREDIT,PERCENT,VALUE
    */
    enum class TargetChargeType(val value: kotlin.String){
        CREDIT("CREDIT"),
        PERCENT("PERCENT"),
        VALUE("VALUE");
    }
}