/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param owner 
 * @param reason 
 * @param sessionId 
 */
data class CancelSessionDto (

    val owner: CancelSessionDto.Owner,
    val reason: kotlin.String,
    val sessionId: kotlin.String
) {
    /**
    * 
    * Values: ALL,CLIENT,LAWYER,LIST
    */
    enum class Owner(val value: kotlin.String){
        ALL("ALL"),
        CLIENT("CLIENT"),
        LAWYER("LAWYER"),
        LIST("LIST");
    }
}