/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param checkoutId 
 * @param reason 
 * @param state 
 */
data class CheckoutInputDto (

    val checkoutId: kotlin.String,
    val reason: kotlin.String? = null,
    val state: CheckoutInputDto.State
) {
    /**
    * 
    * Values: CONFIRMED,FAILED,REQUESTED
    */
    enum class State(val value: kotlin.String){
        CONFIRMED("CONFIRMED"),
        FAILED("FAILED"),
        REQUESTED("REQUESTED");
    }
}