/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.FinalFromToTimeModel

/**
 * 
 * @param consultingType 
 * @param isActive 
 * @param isEnabled 
 * @param responseTime 
 * @param userId 
 * @param workCalender 
 */
data class ConfigurationOutputDto (

    val consultingType: ConfigurationOutputDto.ConsultingType? = null,
    val isActive: kotlin.Boolean? = null,
    val isEnabled: kotlin.Boolean? = null,
    val responseTime: kotlin.Long? = null,
    val userId: kotlin.String? = null,
    val workCalender: kotlin.collections.Map<kotlin.String, FinalFromToTimeModel>? = null
) {
    /**
    * 
    * Values: OFFLINE,ONLINE,URGENT
    */
    enum class ConsultingType(val value: kotlin.String){
        OFFLINE("OFFLINE"),
        ONLINE("ONLINE"),
        URGENT("URGENT");
    }
}