/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ConsultationPackage

/**
 * 
 * @param consultingType 
 * @param createdDate 
 * @param deleted 
 * @param deletedAt 
 * @param id 
 * @param lastModifiedDate 
 * @param lawyerShare 
 * @param new 
 * @param packages 
 * @param version 
 */
data class ConsultationSetting (

    val consultingType: ConsultationSetting.ConsultingType? = null,
    val createdDate: kotlin.String? = null,
    val deleted: kotlin.Boolean? = null,
    val deletedAt: kotlin.String? = null,
    val id: kotlin.String? = null,
    val lastModifiedDate: kotlin.String? = null,
    val lawyerShare: kotlin.Int? = null,
    val new: kotlin.Boolean? = null,
    val packages: kotlin.Array<ConsultationPackage>? = null,
    val version: kotlin.Long? = null
) {
    /**
    * 
    * Values: OFFLINE,ONLINE,URGENT
    */
    enum class ConsultingType(val value: kotlin.String){
        OFFLINE("OFFLINE"),
        ONLINE("ONLINE"),
        URGENT("URGENT");
    }
}