/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param description 
 * @param sendPush 
 * @param sendToAll 
 * @param subscriberIds 
 * @param title 
 * @param userIds 
 */
data class CreateNotificationDto (

    val description: kotlin.String? = null,
    val sendPush: kotlin.Boolean,
    val sendToAll: kotlin.Boolean,
    val subscriberIds: kotlin.Array<kotlin.String>? = null,
    val title: kotlin.String? = null,
    val userIds: kotlin.Array<kotlin.String>? = null
) {
}