/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Owner

/**
 * 
 * @param comment user comment
 * @param negativeOpinions negative opinions
 * @param owners 
 * @param positiveOpinions positive opinions
 * @param value the rate value
 */
data class CreateMultiRateDto (

    /* user comment */
    val comment: kotlin.String? = null,
    /* negative opinions */
    val negativeOpinions: kotlin.Array<kotlin.String>? = null,
    val owners: kotlin.Array<Owner>? = null,
    /* positive opinions */
    val positiveOpinions: kotlin.Array<kotlin.String>? = null,
    /* the rate value */
    val value: kotlin.Int? = null
) {
}