/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.LocationAddressDto

/**
 * 
 * @param address 
 * @param banner 
 * @param categoriesId 
 * @param description 
 * @param email 
 * @param geoCodingType 
 * @param lat 
 * @param lng 
 * @param metaData 
 * @param parentId 
 * @param propertiesId 
 * @param status 
 * @param tagsId 
 * @param title 
 * @param type 
 */
data class CreateLocationDto (

    val address: LocationAddressDto? = null,
    val banner: kotlin.Array<kotlin.String>? = null,
    val categoriesId: kotlin.Array<kotlin.String>? = null,
    val description: kotlin.String? = null,
    val email: kotlin.String? = null,
    val geoCodingType: CreateLocationDto.GeoCodingType? = null,
    val lat: kotlin.Double? = null,
    val lng: kotlin.Double? = null,
    val metaData: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val parentId: kotlin.String? = null,
    val propertiesId: kotlin.Array<kotlin.String>? = null,
    val status: CreateLocationDto.Status,
    val tagsId: kotlin.Array<kotlin.String>? = null,
    val title: kotlin.String? = null,
    val type: kotlin.String
) {
    /**
    * 
    * Values: GOOGLE
    */
    enum class GeoCodingType(val value: kotlin.String){
        GOOGLE("GOOGLE");
    }
    /**
    * 
    * Values: DRAFT,PUBLISHED
    */
    enum class Status(val value: kotlin.String){
        DRAFT("DRAFT"),
        PUBLISHED("PUBLISHED");
    }
}