/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param comment user comment
 * @param metaData 
 * @param negativeOpinions negative opinions
 * @param positiveOpinions positive opinions
 * @param relatedId orderId, productId,...
 * @param value the rate value
 */
data class CreateRateDto (

    /* user comment */
    val comment: kotlin.String? = null,
    val metaData: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    /* negative opinions */
    val negativeOpinions: kotlin.Array<kotlin.String>? = null,
    /* positive opinions */
    val positiveOpinions: kotlin.Array<kotlin.String>? = null,
    /* orderId, productId,... */
    val relatedId: kotlin.String? = null,
    /* the rate value */
    val value: kotlin.Int? = null
) {
}