/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.DiscountType
import io.swagger.client.models.StateMachine_string_

/**
 * 
 * @param createdDate 
 * @param deleted 
 * @param deletedAt 
 * @param description 
 * @param discountCode 
 * @param discountNumber 
 * @param discountType 
 * @param from 
 * @param id 
 * @param lastModifiedDate 
 * @param new 
 * @param stateMachine 
 * @param to 
 * @param usageLimit 
 * @param usersIds 
 * @param version 
 */
data class DiscountRes (

    val createdDate: kotlin.String? = null,
    val deleted: kotlin.Boolean? = null,
    val deletedAt: kotlin.String? = null,
    val description: kotlin.String? = null,
    val discountCode: kotlin.String? = null,
    val discountNumber: kotlin.Int? = null,
    val discountType: DiscountType? = null,
    val from: kotlin.String? = null,
    val id: kotlin.String? = null,
    val lastModifiedDate: kotlin.String? = null,
    val new: kotlin.Boolean? = null,
    val stateMachine: StateMachine_string_? = null,
    val to: kotlin.String? = null,
    val usageLimit: kotlin.Int? = null,
    val usersIds: kotlin.Array<kotlin.String>? = null,
    val version: kotlin.Long? = null
) {
}