/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param degree 
 * @param fieldOfStudy 
 * @param from 
 * @param isStudying 
 * @param to 
 * @param universityName 
 */
data class Education (

    val degree: Education.Degree? = null,
    val fieldOfStudy: kotlin.String? = null,
    val from: kotlin.String? = null,
    val isStudying: kotlin.Boolean? = null,
    val to: kotlin.String? = null,
    val universityName: kotlin.String? = null
) {
    /**
    * 
    * Values: ASSOCIATE,BACHELOR,DIPLOMA,DOCTORATE,MASTER,POSTDOCTORAL
    */
    enum class Degree(val value: kotlin.String){
        ASSOCIATE("ASSOCIATE"),
        BACHELOR("BACHELOR"),
        DIPLOMA("DIPLOMA"),
        DOCTORATE("DOCTORATE"),
        MASTER("MASTER"),
        POSTDOCTORAL("POSTDOCTORAL");
    }
}