/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.FileOrFolder

/**
 * 
 * @param access 
 * @param bucketName 
 * @param childFolders 
 * @param disk 
 * @param fileName 
 * @param filePath 
 * @param id 
 * @param mimeType 
 * @param originalFileName 
 * @param parentId 
 * @param size 
 * @param type 
 * @param uploadedAt 
 * @param url 
 * @param userId 
 */
data class FileOrFolder (

    val access: FileOrFolder.Access? = null,
    val bucketName: kotlin.String? = null,
    val childFolders: kotlin.Array<FileOrFolder>? = null,
    val disk: FileOrFolder.Disk? = null,
    val fileName: kotlin.String? = null,
    val filePath: kotlin.String? = null,
    val id: kotlin.String? = null,
    val mimeType: kotlin.String? = null,
    val originalFileName: kotlin.String? = null,
    val parentId: kotlin.String? = null,
    val size: kotlin.Long? = null,
    val type: FileOrFolder.Type? = null,
    val uploadedAt: kotlin.Long? = null,
    val url: kotlin.String? = null,
    val userId: kotlin.String? = null
) {
    /**
    * 
    * Values: PRIVATE,PUBLIC
    */
    enum class Access(val value: kotlin.String){
        PRIVATE("PRIVATE"),
        PUBLIC("PUBLIC");
    }
    /**
    * 
    * Values: ABRAMAD,ARVAN,BLOB,LOCAL,S3
    */
    enum class Disk(val value: kotlin.String){
        ABRAMAD("ABRAMAD"),
        ARVAN("ARVAN"),
        BLOB("BLOB"),
        LOCAL("LOCAL"),
        S3("S3");
    }
    /**
    * 
    * Values: FILE,FOLDER
    */
    enum class Type(val value: kotlin.String){
        FILE("FILE"),
        FOLDER("FOLDER");
    }
}