/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param from 
 * @param full 
 * @param to 
 */
data class FromToTime (

    val from: kotlin.String? = null,
    val full: kotlin.Boolean? = null,
    val to: kotlin.String? = null
) {
}