/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param &#x60;data&#x60; 
 * @param errors 
 * @param message 
 */
data class GenericResponseDto_object_ (

    val `data`: kotlin.Any? = null,
    val errors: kotlin.collections.Map<kotlin.String, kotlin.Array<kotlin.String>>? = null,
    val message: kotlin.String? = null
) {
}