/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param comment 
 * @param commentStatus 
 * @param commenterEmail 
 * @param commenterName 
 * @param createdDate 
 * @param id 
 * @param relatedPostId 
 */
data class GetCommentDto (

    val comment: kotlin.String? = null,
    val commentStatus: GetCommentDto.CommentStatus? = null,
    val commenterEmail: kotlin.String? = null,
    val commenterName: kotlin.String? = null,
    val createdDate: kotlin.String? = null,
    val id: kotlin.String? = null,
    val relatedPostId: kotlin.String? = null
) {
    /**
    * 
    * Values: DRAFT,PUBLISHED,REJECTED
    */
    enum class CommentStatus(val value: kotlin.String){
        DRAFT("DRAFT"),
        PUBLISHED("PUBLISHED"),
        REJECTED("REJECTED");
    }
}