/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param avatar 
 * @param comment 
 * @param createdDate 
 * @param firstName 
 * @param lastName 
 */
data class GetComment (

    val avatar: kotlin.String? = null,
    val comment: kotlin.String? = null,
    val createdDate: kotlin.String? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null
) {
}