/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param categoryName 
 * @param consultingCost 
 * @param consultingName 
 * @param decreaseWalletAmount 
 * @param discountAmount 
 * @param lawyerAvatar 
 * @param lawyerFirstName 
 * @param lawyerGradeEnum 
 * @param lawyerLastName 
 * @param payableAmount 
 * @param userBalance 
 */
data class GetInvoiceInformationDto (

    val categoryName: kotlin.String? = null,
    val consultingCost: kotlin.Double? = null,
    val consultingName: GetInvoiceInformationDto.ConsultingName? = null,
    val decreaseWalletAmount: kotlin.Double? = null,
    val discountAmount: kotlin.Double? = null,
    val lawyerAvatar: kotlin.String? = null,
    val lawyerFirstName: kotlin.String? = null,
    val lawyerGradeEnum: kotlin.String? = null,
    val lawyerLastName: kotlin.String? = null,
    val payableAmount: kotlin.Double? = null,
    val userBalance: kotlin.Double? = null
) {
    /**
    * 
    * Values: OFFLINE,ONLINE,URGENT
    */
    enum class ConsultingName(val value: kotlin.String){
        OFFLINE("OFFLINE"),
        ONLINE("ONLINE"),
        URGENT("URGENT");
    }
}