/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.SenderInfo

/**
 * 
 * @param createdDateMilli 
 * @param description 
 * @param id 
 * @param receiverInfo 
 * @param senderInfo 
 * @param subscriberIds 
 * @param title 
 * @param userIds 
 */
data class GetNotificationDto (

    val createdDateMilli: kotlin.Long? = null,
    val description: kotlin.String? = null,
    val id: kotlin.String? = null,
    val receiverInfo: kotlin.String? = null,
    val senderInfo: SenderInfo? = null,
    val subscriberIds: kotlin.Array<kotlin.String>? = null,
    val title: kotlin.String? = null,
    val userIds: kotlin.Array<kotlin.String>? = null
) {
}