/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param comment 
 * @param id 
 * @param metaData 
 * @param negativeOpinions 
 * @param positiveOpinions 
 * @param relatedId 
 * @param value 
 */
data class GetRateDto (

    val comment: kotlin.String? = null,
    val id: kotlin.String? = null,
    val metaData: kotlin.Any? = null,
    val negativeOpinions: kotlin.Array<kotlin.String>? = null,
    val positiveOpinions: kotlin.Array<kotlin.String>? = null,
    val relatedId: kotlin.String? = null,
    val value: kotlin.Int? = null
) {
}