/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param description 
 * @param negativeOpinions 
 * @param positiveOpinions 
 * @param rateValueEnum 
 * @param title 
 */
data class GetRateOpinionDto (

    val description: kotlin.String? = null,
    val negativeOpinions: kotlin.Array<kotlin.String>? = null,
    val positiveOpinions: kotlin.Array<kotlin.String>? = null,
    val rateValueEnum: GetRateOpinionDto.RateValueEnum? = null,
    val title: kotlin.String? = null
) {
    /**
    * 
    * Values: FIVE,FOUR,ONE,THREE,TWO
    */
    enum class RateValueEnum(val value: kotlin.String){
        FIVE("FIVE"),
        FOUR("FOUR"),
        ONE("ONE"),
        THREE("THREE"),
        TWO("TWO");
    }
}