/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param birthdate 
 * @param city 
 * @param firstName 
 * @param lastName 
 * @param nationalCode 
 * @param password 
 * @param province 
 */
data class InitialProfileLawyerDto (

    val birthdate: kotlin.String? = null,
    val city: kotlin.String,
    val firstName: kotlin.String,
    val lastName: kotlin.String,
    val nationalCode: kotlin.String,
    val password: kotlin.String? = null,
    val province: kotlin.String
) {
}