/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param key 
 * @param statusEnum 
 * @param valueEnum 
 */
data class KeyQueryParam (

    val key: kotlin.String,
    val statusEnum: KeyQueryParam.StatusEnum,
    val valueEnum: KeyQueryParam.ValueEnum
) {
    /**
    * 
    * Values: NEGATIVE,POSITIVE
    */
    enum class StatusEnum(val value: kotlin.String){
        NEGATIVE("NEGATIVE"),
        POSITIVE("POSITIVE");
    }
    /**
    * 
    * Values: FIVE,FOUR,ONE,THREE,TWO
    */
    enum class ValueEnum(val value: kotlin.String){
        FIVE("FIVE"),
        FOUR("FOUR"),
        ONE("ONE"),
        THREE("THREE"),
        TWO("TWO");
    }
}