/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param language 
 * @param languageLevel 
 */
data class LanguageModel (

    val language: kotlin.String? = null,
    val languageLevel: LanguageModel.LanguageLevel? = null
) {
    /**
    * 
    * Values: BEGINNER,MID,NATIVE,PRO
    */
    enum class LanguageLevel(val value: kotlin.String){
        BEGINNER("BEGINNER"),
        MID("MID"),
        NATIVE("NATIVE"),
        PRO("PRO");
    }
}