/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.LawyerGradeModel

/**
 * 
 * @param grades 
 * @param key 
 * @param title 
 */
data class LawyerCategoryModel (

    val grades: kotlin.Array<LawyerGradeModel>? = null,
    val key: LawyerCategoryModel.Key? = null,
    val title: kotlin.String? = null
) {
    /**
    * 
    * Values: KANOONDADGOSTARI,KARSEHNASHOGHOOGHI,MARKAZVOKALA
    */
    enum class Key(val value: kotlin.String){
        KANOONDADGOSTARI("KANOON_DADGOSTARI"),
        KARSEHNASHOGHOOGHI("KARSEHNAS_HOGHOOGHI"),
        MARKAZVOKALA("MARKAZ_VOKALA");
    }
}