/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ProfessionalProfileDTO

/**
 * 
 * @param commentsCount 
 * @param professionalProfile 
 * @param rate 
 * @param totalConsultingCount 
 */
data class LawyerConsultingDto (

    val commentsCount: kotlin.Int? = null,
    val professionalProfile: ProfessionalProfileDTO? = null,
    val rate: kotlin.Float? = null,
    val totalConsultingCount: kotlin.Int? = null
) {
}