/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param lawyerCategory 
 * @param lawyerGrade 
 */
data class LawyerTypeDto (

    val lawyerCategory: LawyerTypeDto.LawyerCategory? = null,
    val lawyerGrade: LawyerTypeDto.LawyerGrade? = null
) {
    /**
    * 
    * Values: KANOONDADGOSTARI,KARSEHNASHOGHOOGHI,MARKAZVOKALA
    */
    enum class LawyerCategory(val value: kotlin.String){
        KANOONDADGOSTARI("KANOON_DADGOSTARI"),
        KARSEHNASHOGHOOGHI("KARSEHNAS_HOGHOOGHI"),
        MARKAZVOKALA("MARKAZ_VOKALA");
    }
    /**
    * 
    * Values: KANOONDADGOSTARIKARAMOOZ,KANOONDADGOSTARIPAYE1,KANOONDADGOSTARIPAYE2,KARSEHNASHOGHOOGHI,MARKAZVOKALAKARAMOOZ,MARKAZVOKALAPAYE1,MARKAZVOKALAPAYE2
    */
    enum class LawyerGrade(val value: kotlin.String){
        KANOONDADGOSTARIKARAMOOZ("KANOON_DADGOSTARI_KARAMOOZ"),
        KANOONDADGOSTARIPAYE1("KANOON_DADGOSTARI_PAYE_1"),
        KANOONDADGOSTARIPAYE2("KANOON_DADGOSTARI_PAYE_2"),
        KARSEHNASHOGHOOGHI("KARSEHNAS_HOGHOOGHI"),
        MARKAZVOKALAKARAMOOZ("MARKAZ_VOKALA_KARAMOOZ"),
        MARKAZVOKALAPAYE1("MARKAZ_VOKALA_PAYE_1"),
        MARKAZVOKALAPAYE2("MARKAZ_VOKALA_PAYE_2");
    }
}