/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param city 
 * @param country 
 * @param gid 
 * @param route 
 * @param state 
 */
data class LocationAddressDto (

    val city: kotlin.String? = null,
    val country: kotlin.String? = null,
    val gid: kotlin.String? = null,
    val route: kotlin.String? = null,
    val state: kotlin.String? = null
) {
}