/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param createdDate 
 * @param id 
 * @param ids 
 * @param isRead 
 * @param message 
 * @param metaData 
 * @param title 
 */
data class NotificationDto (

    val createdDate: kotlin.String? = null,
    val id: kotlin.String? = null,
    val ids: kotlin.Array<kotlin.String>? = null,
    val isRead: kotlin.Boolean? = null,
    val message: kotlin.String? = null,
    val metaData: kotlin.Any? = null,
    val title: kotlin.String? = null
) {
}