/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param aboutMe 
 * @param address 
 * @param gender 
 */
data class PersonalInformationDTO (

    val aboutMe: kotlin.String? = null,
    val address: kotlin.String? = null,
    val gender: PersonalInformationDTO.Gender
) {
    /**
    * 
    * Values: FEMALE,MALE,NONE
    */
    enum class Gender(val value: kotlin.String){
        FEMALE("FEMALE"),
        MALE("MALE"),
        NONE("NONE");
    }
}