/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.Capability
import io.swagger.client.models.Education
import io.swagger.client.models.LanguageModel
import io.swagger.client.models.PersonalInformationReq
import io.swagger.client.models.Research
import io.swagger.client.models.Resume

/**
 * 
 * @param aboutMe 
 * @param address 
 * @param capabilities 
 * @param city 
 * @param dateOfIssue 
 * @param degree 
 * @param educations 
 * @param gender 
 * @param languages 
 * @param licenseCode 
 * @param licenseFileId 
 * @param personalInformation 
 * @param profileImageId 
 * @param province 
 * @param researches 
 * @param resumes 
 * @param userId 
 */
data class ProfessionalInputDTO (

    val aboutMe: kotlin.String? = null,
    val address: kotlin.String? = null,
    val capabilities: kotlin.Array<Capability>? = null,
    val city: kotlin.String? = null,
    val dateOfIssue: kotlin.String? = null,
    val degree: ProfessionalInputDTO.Degree? = null,
    val educations: kotlin.Array<Education>? = null,
    val gender: ProfessionalInputDTO.Gender? = null,
    val languages: kotlin.Array<LanguageModel>? = null,
    val licenseCode: kotlin.String? = null,
    val licenseFileId: kotlin.String? = null,
    val personalInformation: PersonalInformationReq? = null,
    val profileImageId: kotlin.String? = null,
    val province: kotlin.String? = null,
    val researches: kotlin.Array<Research>? = null,
    val resumes: kotlin.Array<Resume>? = null,
    val userId: kotlin.String? = null
) {
    /**
    * 
    * Values: ASSOCIATE,BACHELOR,DIPLOMA,DOCTORATE,MASTER,POSTDOCTORAL
    */
    enum class Degree(val value: kotlin.String){
        ASSOCIATE("ASSOCIATE"),
        BACHELOR("BACHELOR"),
        DIPLOMA("DIPLOMA"),
        DOCTORATE("DOCTORATE"),
        MASTER("MASTER"),
        POSTDOCTORAL("POSTDOCTORAL");
    }
    /**
    * 
    * Values: FEMALE,MALE,NONE
    */
    enum class Gender(val value: kotlin.String){
        FEMALE("FEMALE"),
        MALE("MALE"),
        NONE("NONE");
    }
}