/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param body 
 * @param &#x60;data&#x60; 
 * @param id 
 * @param notifiableId 
 * @param priority 
 * @param subscriberId 
 * @param title 
 * @param userId 
 */
data class PushMessageDto (

    val body: kotlin.String? = null,
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val id: kotlin.String? = null,
    val notifiableId: kotlin.String? = null,
    val priority: kotlin.String? = null,
    val subscriberId: kotlin.String? = null,
    val title: kotlin.String? = null,
    val userId: kotlin.String? = null
) {
}