/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param appName 
 * @param fcmAdminSdkJson 
 * @param id 
 */
data class PushServerDto (

    val appName: kotlin.String? = null,
    val fcmAdminSdkJson: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,
    val id: kotlin.String? = null
) {
}