/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param comment 
 * @param fullName 
 * @param id 
 * @param rating 
 * @param ticketId 
 */
data class RateDto (

    val comment: kotlin.String? = null,
    val fullName: kotlin.String? = null,
    val id: kotlin.String? = null,
    val rating: kotlin.Float? = null,
    val ticketId: kotlin.String? = null
) {
}