/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.FromToTime
import io.swagger.client.models.SessionHistory
import io.swagger.client.models.SessionMessage

/**
 * 
 * @param cancelRequestDateTime 
 * @param cancellationOwner 
 * @param cancellationReason 
 * @param categoryId 
 * @param consultingCost 
 * @param createdDate 
 * @param deleted 
 * @param deletedAt 
 * @param duration 
 * @param extendRequestDateTime 
 * @param histories 
 * @param id 
 * @param isCancelRequested 
 * @param isExtendRequested 
 * @param isNotifySend 
 * @param lastModifiedDate 
 * @param lawyerId 
 * @param new 
 * @param numberOfRemainingQuestions 
 * @param orderNumber 
 * @param packageId 
 * @param roomId 
 * @param selectedDate 
 * @param selectedTime 
 * @param sessionEndTime 
 * @param sessionMessages 
 * @param sessionStartTime 
 * @param skillId 
 * @param state 
 * @param turn 
 * @param type 
 * @param userId 
 * @param version 
 */
data class Session (

    val cancelRequestDateTime: kotlin.String? = null,
    val cancellationOwner: Session.CancellationOwner? = null,
    val cancellationReason: kotlin.String? = null,
    val categoryId: kotlin.String? = null,
    val consultingCost: kotlin.Double? = null,
    val createdDate: kotlin.String? = null,
    val deleted: kotlin.Boolean? = null,
    val deletedAt: kotlin.String? = null,
    val duration: kotlin.Long? = null,
    val extendRequestDateTime: kotlin.String? = null,
    val histories: kotlin.Array<SessionHistory>? = null,
    val id: kotlin.String? = null,
    val isCancelRequested: kotlin.Boolean? = null,
    val isExtendRequested: kotlin.Boolean? = null,
    val isNotifySend: kotlin.Boolean? = null,
    val lastModifiedDate: kotlin.String? = null,
    val lawyerId: kotlin.String? = null,
    val new: kotlin.Boolean? = null,
    val numberOfRemainingQuestions: kotlin.Int? = null,
    val orderNumber: kotlin.String? = null,
    val packageId: kotlin.String? = null,
    val roomId: kotlin.String? = null,
    val selectedDate: kotlin.String? = null,
    val selectedTime: FromToTime? = null,
    val sessionEndTime: kotlin.String? = null,
    val sessionMessages: kotlin.Array<SessionMessage>? = null,
    val sessionStartTime: kotlin.String? = null,
    val skillId: kotlin.String? = null,
    val state: Session.State? = null,
    val turn: Session.Turn? = null,
    val type: Session.Type? = null,
    val userId: kotlin.String? = null,
    val version: kotlin.Long? = null
) {
    /**
    * 
    * Values: ALL,CLIENT,LAWYER,LIST
    */
    enum class CancellationOwner(val value: kotlin.String){
        ALL("ALL"),
        CLIENT("CLIENT"),
        LAWYER("LAWYER"),
        LIST("LIST");
    }
    /**
    * 
    * Values: CANCELED,CREATED,DONE,FINISHEDCREATED,FINISHEDRESERVED,PENDING,RESERVED,RESERVEDSTARTTIMESET
    */
    enum class State(val value: kotlin.String){
        CANCELED("CANCELED"),
        CREATED("CREATED"),
        DONE("DONE"),
        FINISHEDCREATED("FINISHED_CREATED"),
        FINISHEDRESERVED("FINISHED_RESERVED"),
        PENDING("PENDING"),
        RESERVED("RESERVED"),
        RESERVEDSTARTTIMESET("RESERVED_START_TIME_SET");
    }
    /**
    * 
    * Values: ALL,CLIENT,LAWYER,LIST
    */
    enum class Turn(val value: kotlin.String){
        ALL("ALL"),
        CLIENT("CLIENT"),
        LAWYER("LAWYER"),
        LIST("LIST");
    }
    /**
    * 
    * Values: OFFLINE,ONLINE,URGENT
    */
    enum class Type(val value: kotlin.String){
        OFFLINE("OFFLINE"),
        ONLINE("ONLINE"),
        URGENT("URGENT");
    }
}