/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ConsultationPackageDto

/**
 * 
 * @param consultingType 
 * @param lawyerShare 
 * @param packages 
 */
data class SettingInputDto (

    val consultingType: SettingInputDto.ConsultingType,
    val lawyerShare: kotlin.Int,
    val packages: kotlin.Array<ConsultationPackageDto>
) {
    /**
    * 
    * Values: OFFLINE,ONLINE,URGENT
    */
    enum class ConsultingType(val value: kotlin.String){
        OFFLINE("OFFLINE"),
        ONLINE("ONLINE"),
        URGENT("URGENT");
    }
}