/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param active 
 * @param id 
 * @param password 
 * @param shortNumber 
 * @param smsAgent 
 * @param url 
 * @param username 
 */
data class SmsServerDto (

    val active: kotlin.Boolean? = null,
    val id: kotlin.String? = null,
    val password: kotlin.String? = null,
    val shortNumber: kotlin.String? = null,
    val smsAgent: SmsServerDto.SmsAgent? = null,
    val url: kotlin.String? = null,
    val username: kotlin.String? = null
) {
    /**
    * 
    * Values: DUMMY,KAVEHVERIFICATION,KAVENEGAR,TWILIO
    */
    enum class SmsAgent(val value: kotlin.String){
        DUMMY("DUMMY"),
        KAVEHVERIFICATION("KAVEH_VERIFICATION"),
        KAVENEGAR("KAVE_NEGAR"),
        TWILIO("TWILIO");
    }
}