/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param empty 
 * @param sorted 
 * @param unsorted 
 */
data class Sort (

    val empty: kotlin.Boolean? = null,
    val sorted: kotlin.Boolean? = null,
    val unsorted: kotlin.Boolean? = null
) {
}