/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param at 
 * @param state 
 */
data class StateDto_string_ (

    val at: kotlin.Long? = null,
    val state: StateDto_string_.State? = null
) {
    /**
    * 
    * Values: CLOSED,OPENED,PROCESSING
    */
    enum class State(val value: kotlin.String){
        CLOSED("CLOSED"),
        OPENED("OPENED"),
        PROCESSING("PROCESSING");
    }
}