/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param at 
 * @param state 
 */
data class State_string_ (

    val at: kotlin.String? = null,
    val state: State_string_.State? = null
) {
    /**
    * 
    * Values: CANCELED,CONFIRMATIONRECEIVED,PREPROCESSED,REDIRECTEDTOGATEWAY,RETURNEDFROMGATEWAY
    */
    enum class State(val value: kotlin.String){
        CANCELED("CANCELED"),
        CONFIRMATIONRECEIVED("CONFIRMATION_RECEIVED"),
        PREPROCESSED("PREPROCESSED"),
        REDIRECTEDTOGATEWAY("REDIRECTED_TO_GATEWAY"),
        RETURNEDFROMGATEWAY("RETURNED_FROM_GATEWAY");
    }
}