/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.StateMachine_string_

/**
 * 
 * @param amount 
 * @param paymentToken 
 * @param stateMachine 
 * @param subscriberId 
 * @param userId 
 */
data class TransactionDto (

    val amount: kotlin.Double? = null,
    val paymentToken: kotlin.String? = null,
    val stateMachine: StateMachine_string_? = null,
    val subscriberId: kotlin.String? = null,
    val userId: kotlin.String? = null
) {
}