/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param description 
 * @param from 
 * @param to 
 * @param usersIds 
 * @param value 
 */
data class UpdateChargeDto (

    val description: kotlin.String? = null,
    val from: kotlin.String? = null,
    val to: kotlin.String? = null,
    val usersIds: kotlin.Array<kotlin.String>? = null,
    val value: kotlin.Int? = null
) {
}