/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.MetaData

/**
 * 
 * @param applicationName The application name
 * @param applicationType OS type
 * @param link Download link
 * @param metaData 
 * @param packageName Same as bundle id in apple ecosystem
 * @param updateMode Update mode
 * @param versionCode Same as build number in apple ecosystem
 * @param versionName Insert version without any string  valid data: 1.2.4 , 13.223.433  invalid data : 1.2 , 1.3.0.Beta
 */
data class UpdateApplicationVersion (

    /* The application name */
    val applicationName: kotlin.String? = null,
    /* OS type */
    val applicationType: UpdateApplicationVersion.ApplicationType? = null,
    /* Download link */
    val link: kotlin.String? = null,
    val metaData: MetaData? = null,
    /* Same as bundle id in apple ecosystem */
    val packageName: kotlin.String? = null,
    /* Update mode */
    val updateMode: UpdateApplicationVersion.UpdateMode? = null,
    /* Same as build number in apple ecosystem */
    val versionCode: kotlin.String? = null,
    /* Insert version without any string  valid data: 1.2.4 , 13.223.433  invalid data : 1.2 , 1.3.0.Beta */
    val versionName: kotlin.String? = null
) {
    /**
    * OS type
    * Values: ANDROID,IOS
    */
    enum class ApplicationType(val value: kotlin.String){
        ANDROID("ANDROID"),
        IOS("IOS");
    }
    /**
    * Update mode
    * Values: FORCE,RECOMMENDED
    */
    enum class UpdateMode(val value: kotlin.String){
        FORCE("FORCE"),
        RECOMMENDED("RECOMMENDED");
    }
}