/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param address 
 * @param city 
 * @param lat 
 * @param lon 
 * @param province 
 */
data class UserPersonalAddressDto (

    val address: kotlin.String? = null,
    val city: kotlin.String? = null,
    val lat: kotlin.Float? = null,
    val lon: kotlin.Float? = null,
    val province: kotlin.String? = null
) {
}