/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.DiscountType

/**
 * 
 * @param discountAmount 
 * @param paymentAmount 
 * @param type 
 */
data class ValidateDiscountAmountDto (

    val discountAmount: kotlin.Double? = null,
    val paymentAmount: kotlin.Double? = null,
    val type: DiscountType? = null
) {
}