/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param amount 
 * @param bankGatewayId 
 * @param clientCallbackUrl 
 * @param createDateIso 
 * @param createdDateMilli 
 * @param currentState 
 * @param description 
 * @param id 
 * @param paymentLink 
 * @param refId 
 * @param relatedId fill if you want to remember sth
 * @param subscriberId 
 * @param userId 
 * @param walletTransactionType 
 */
data class WalletTransactionDto (

    val amount: kotlin.Long? = null,
    val bankGatewayId: kotlin.String? = null,
    val clientCallbackUrl: kotlin.String? = null,
    val createDateIso: kotlin.String? = null,
    val createdDateMilli: kotlin.Long? = null,
    val currentState: WalletTransactionDto.CurrentState? = null,
    val description: kotlin.String? = null,
    val id: kotlin.String? = null,
    val paymentLink: kotlin.String? = null,
    val refId: kotlin.String? = null,
    /* fill if you want to remember sth */
    val relatedId: kotlin.String? = null,
    val subscriberId: kotlin.String? = null,
    val userId: kotlin.String? = null,
    val walletTransactionType: WalletTransactionDto.WalletTransactionType? = null
) {
    /**
    * 
    * Values: DONE,WAITINGFORIPGRESPONSE
    */
    enum class CurrentState(val value: kotlin.String){
        DONE("DONE"),
        WAITINGFORIPGRESPONSE("WAITING_FOR_IPG_RESPONSE");
    }
    /**
    * 
    * Values: DEBIT,DEPOSIT,DEPOSITREMAINING
    */
    enum class WalletTransactionType(val value: kotlin.String){
        DEBIT("DEBIT"),
        DEPOSIT("DEPOSIT"),
        DEPOSITREMAINING("DEPOSIT_REMAINING");
    }
}