/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param gatewayType 
 * @param thirdPartyAccountId 
 */
data class WalletAccountDto (

    val gatewayType: WalletAccountDto.GatewayType? = null,
    val thirdPartyAccountId: kotlin.String? = null
) {
    /**
    * 
    * Values: PAYMONGO,SEP,STRIPE,TEJARAT,TEST,ZARRINPAL
    */
    enum class GatewayType(val value: kotlin.String){
        PAYMONGO("PAYMONGO"),
        SEP("SEP"),
        STRIPE("STRIPE"),
        TEJARAT("TEJARAT"),
        TEST("TEST"),
        ZARRINPAL("ZARRIN_PAL");
    }
}