/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.DiscountUserLogDtoReq
import io.swagger.client.models.DiscountUserLogDtoRes
import io.swagger.client.models.DiscountUserLogValidModel
import io.swagger.client.models.DiscountValidationDto
import io.swagger.client.models.Page_DiscountUserLogDto_
import io.swagger.client.models.UsageReportDto
import io.swagger.client.models.ValidateDiscountAmountDto

import io.swagger.client.infrastructure.*

class DiscountUserLogControllerApi(basePath: kotlin.String = "https://datyar.vaslapp.com:443") : ApiClient(basePath) {

    /**
     * create
     *  create discount
     * @param code code 
     * @param acceptLanguage language (optional)
     * @return DiscountUserLogDtoRes
     */
    @Suppress("UNCHECKED_CAST")
    fun createDiscountUserLog(code: kotlin.String, acceptLanguage: kotlin.String? = null): DiscountUserLogDtoRes {
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/v1/discount/discount-userlog/{code}".replace("{" + "code" + "}", "$code"), headers = localVariableHeaders
        )
        val response = request<DiscountUserLogDtoRes>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as DiscountUserLogDtoRes
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * deleteDiscountUserLog
     * 
     * @param id id 
     * @param acceptLanguage language (optional)
     * @return void
     */
    fun deleteDiscountUserLog(id: kotlin.String, acceptLanguage: kotlin.String? = null): Unit {
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/api/v1/discount/discount-userlog/{id}".replace("{" + "id" + "}", "$id"), headers = localVariableHeaders
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * getDiscountLogFilter
     * 
     * @param acceptLanguage language (optional)
     * @param discountCode  (optional)
     * @param from  (optional)
     * @param pageNumber starts from 0 (optional)
     * @param pageSize must be greater than 0 (optional)
     * @param sort ASC&#x3D;ascending ,DESC&#x3D;descending (optional)
     * @param sortKey sort will be based on these words (optional)
     * @param to  (optional)
     * @param usersId  (optional)
     * @return Page_DiscountUserLogDto_
     */
    @Suppress("UNCHECKED_CAST")
    fun getDiscountLogFilter1(acceptLanguage: kotlin.String? = null, discountCode: kotlin.String? = null, from: kotlin.Long? = null, pageNumber: kotlin.Int? = null, pageSize: kotlin.Int? = null, sort: kotlin.String? = null, sortKey: kotlin.Array<kotlin.String>? = null, to: kotlin.Long? = null, usersId: kotlin.String? = null): Page_DiscountUserLogDto_ {
        val localVariableQuery: MultiValueMap = mapOf("discountCode" to listOf("$discountCode"), "from" to listOf("$from"), "pageNumber" to listOf("$pageNumber"), "pageSize" to listOf("$pageSize"), "sort" to listOf("$sort"), "sortKey" to toMultiValue(sortKey!!.toList(), "multi"), "to" to listOf("$to"), "usersId" to listOf("$usersId"))
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/discount/discount-userlog/filter/", query = localVariableQuery, headers = localVariableHeaders
        )
        val response = request<Page_DiscountUserLogDto_>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Page_DiscountUserLogDto_
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * getDiscountUserLog
     * 
     * @param id id 
     * @param acceptLanguage language (optional)
     * @return DiscountUserLogDtoRes
     */
    @Suppress("UNCHECKED_CAST")
    fun getDiscountUserLog(id: kotlin.String, acceptLanguage: kotlin.String? = null): DiscountUserLogDtoRes {
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/discount/discount-userlog/{id}".replace("{" + "id" + "}", "$id"), headers = localVariableHeaders
        )
        val response = request<DiscountUserLogDtoRes>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as DiscountUserLogDtoRes
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * getListDiscountUserLog
     * 
     * @param acceptLanguage language (optional)
     * @param pageNumber starts from 0 (optional)
     * @param pageSize must be greater than 0 (optional)
     * @param sort ASC&#x3D;ascending ,DESC&#x3D;descending (optional)
     * @param sortKey sort will be based on these words (optional)
     * @return Page_DiscountUserLogDto_
     */
    @Suppress("UNCHECKED_CAST")
    fun getListDiscountUserLog(acceptLanguage: kotlin.String? = null, pageNumber: kotlin.Int? = null, pageSize: kotlin.Int? = null, sort: kotlin.String? = null, sortKey: kotlin.Array<kotlin.String>? = null): Page_DiscountUserLogDto_ {
        val localVariableQuery: MultiValueMap = mapOf("pageNumber" to listOf("$pageNumber"), "pageSize" to listOf("$pageSize"), "sort" to listOf("$sort"), "sortKey" to toMultiValue(sortKey!!.toList(), "multi"))
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/discount/discount-userlog", query = localVariableQuery, headers = localVariableHeaders
        )
        val response = request<Page_DiscountUserLogDto_>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Page_DiscountUserLogDto_
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * getUsageReport
     * 
     * @param acceptLanguage language (optional)
     * @param discountCode  (optional)
     * @param from  (optional)
     * @param to  (optional)
     * @return UsageReportDto
     */
    @Suppress("UNCHECKED_CAST")
    fun getUsageReport1(acceptLanguage: kotlin.String? = null, discountCode: kotlin.String? = null, from: kotlin.Long? = null, to: kotlin.Long? = null): UsageReportDto {
        val localVariableQuery: MultiValueMap = mapOf("discountCode" to listOf("$discountCode"), "from" to listOf("$from"), "to" to listOf("$to"))
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/discount/discount-userlog/report/usage", query = localVariableQuery, headers = localVariableHeaders
        )
        val response = request<UsageReportDto>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UsageReportDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * getValidationUser
     * 
     * @param discountCode discountCode 
     * @param acceptLanguage language (optional)
     * @return DiscountUserLogValidModel
     */
    @Suppress("UNCHECKED_CAST")
    fun getValidationUser(discountCode: kotlin.String, acceptLanguage: kotlin.String? = null): DiscountUserLogValidModel {
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/discount/discount-userlog/valid/{discountCode}".replace("{" + "discountCode" + "}", "$discountCode"), headers = localVariableHeaders
        )
        val response = request<DiscountUserLogValidModel>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as DiscountUserLogValidModel
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * Update
     *  update discount
     * @param id id 
     * @param body  (optional)
     * @param acceptLanguage language (optional)
     * @return void
     */
    fun updateDiscountUserLog(id: kotlin.String, body: DiscountUserLogDtoReq? = null, acceptLanguage: kotlin.String? = null): Unit {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/api/v1/discount/discount-userlog/{id}".replace("{" + "id" + "}", "$id"), headers = localVariableHeaders
        )
        val response = request<Any?>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * validateCodeWithAmount
     * 
     * @param body  (optional)
     * @param acceptLanguage language (optional)
     * @return ValidateDiscountAmountDto
     */
    @Suppress("UNCHECKED_CAST")
    fun validateCodeWithAmount(body: DiscountValidationDto? = null, acceptLanguage: kotlin.String? = null): ValidateDiscountAmountDto {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/v1/discount/discount-userlog/validate", headers = localVariableHeaders
        )
        val response = request<ValidateDiscountAmountDto>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as ValidateDiscountAmountDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * validateDiscountByCodeAndAmount
     * 
     * @param code code 
     * @param amount amount 
     * @param acceptLanguage language (optional)
     * @return ValidateDiscountAmountDto
     */
    @Suppress("UNCHECKED_CAST")
    fun validateDiscountByCodeAndAmount1(code: kotlin.String, amount: kotlin.Double, acceptLanguage: kotlin.String? = null): ValidateDiscountAmountDto {
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/v1/discount/discount-userlog/validate/{code}/{amount}".replace("{" + "code" + "}", "$code").replace("{" + "amount" + "}", "$amount"), headers = localVariableHeaders
        )
        val response = request<ValidateDiscountAmountDto>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as ValidateDiscountAmountDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
