/**
 * Datyar REST APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.ForgetPasswordInputDto
import io.swagger.client.models.GenericResponseDto_object_
import io.swagger.client.models.ResetPasswordInputDto

import io.swagger.client.infrastructure.*

class PasswordControllerApi(basePath: kotlin.String = "https://datyar.vaslapp.com:443") : ApiClient(basePath) {

    /**
     * forget
     * 
     * @param body  (optional)
     * @param acceptLanguage language (optional)
     * @return GenericResponseDto_object_
     */
    @Suppress("UNCHECKED_CAST")
    fun forget(body: ForgetPasswordInputDto? = null, acceptLanguage: kotlin.String? = null): GenericResponseDto_object_ {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/client/v1/password/forget", headers = localVariableHeaders
        )
        val response = request<GenericResponseDto_object_>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as GenericResponseDto_object_
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * reset
     * 
     * @param body  (optional)
     * @param acceptLanguage language (optional)
     * @return GenericResponseDto_object_
     */
    @Suppress("UNCHECKED_CAST")
    fun reset(body: ResetPasswordInputDto? = null, acceptLanguage: kotlin.String? = null): GenericResponseDto_object_ {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Accept-Language" to acceptLanguage.toString())
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/client/v1/password/reset", headers = localVariableHeaders
        )
        val response = request<GenericResponseDto_object_>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as GenericResponseDto_object_
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
